name: Pull Request Checks

on: pull_request
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Check style
        run: ./gradlew ktlintCheck
